@base = http://localhost:2333/

### 
PATCH {{base}}options/commentOptions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWE0ZmU2MzI1MDdiYTEyOGY0YzkzOGMiLCJhdXRoQ29kZSI6ImpSMmFhbUoxczEiLCJpYXQiOjE1OTQzNTQxMjIsImV4cCI6MTU5NDk1ODkyMn0.yEknO-VKbsauvcb4iT3jgzyj883vbeJDEu6sEmMcyCg

{
  "antiSpam": true,
  "spamKeywords": ["购买", "刷单"]
}